spring.application.name=reactchat

spring.datasource.url=jdbc:mysql://13.125.254.58:3306/react_chat?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=ighook
spring.datasource.password=fkfmskzk01!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver